# Generated by Django 5.2.5 on 2026-05-01 18:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Egreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Compra de pollo, pago de luz, arriendo', max_length=150, verbose_name='Nombre del Gasto')),
                ('descripcion', models.TextField(blank=True, help_text='Detalles adicionales del gasto', null=True, verbose_name='Descripción')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Gastado')),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta'), ('otro', 'Otro')], default='efectivo', max_length=20, verbose_name='Método de Pago')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha del Gasto')),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='egresos/comprobantes/', verbose_name='Comprobante (opcional)')),
            ],
            options={
                'verbose_name': 'Egreso',
                'verbose_name_plural': 'Egresos',
                'ordering': ['-fecha'],
            },
        ),
    ]
